# Generated by Django 5.2.5 on 2025-08-14 21:24

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bestelling', 'verbose_name_plural': 'Bestellingen'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Bestelling Item', 'verbose_name_plural': 'Bestelling Items'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-is_featured', '-created_at'], 'verbose_name': 'Product', 'verbose_name_plural': 'Producten'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product')},
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_incl_btw',
        ),
        migrations.AddField(
            model_name='order',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='Admin notities'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_notes',
            field=models.TextField(blank=True, verbose_name='Klant opmerkingen'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ideal_bank',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(db_index=True, default='TEMP-ORDER', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='ideal', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Wachtend op betaling'), ('paid', 'Betaald'), ('failed', 'Mislukt'), ('refunded', 'Terugbetaald')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.21'), max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_sku',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, help_text='Belangrijke productkenmerken (één per regel)'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Product afbeelding (max 5MB)', null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured product op homepage'),
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=10, help_text='Waarschuwing bij lage voorraad'),
        ),
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Oorspronkelijke prijs (voor kortingen)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Prijs inclusief 21% BTW in EUR (zoals weergegeven aan klanten)', max_digits=8),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, help_text='Korte beschrijving voor zoekresultaten (max 160 karakters)', max_length=160),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock Keeping Unit (wordt automatisch gegenereerd)', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'In afwachting'), ('confirmed', 'Bevestigd'), ('processing', 'In behandeling'), ('shipped', 'Verzonden'), ('delivered', 'Geleverd'), ('cancelled', 'Geannuleerd')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('honing', 'Biologische Honing'), ('manuka', 'Manuka Honing'), ('cupping', 'Cupping Tools & Sets'), ('cupping_cups', 'Cupping Cups'), ('cupping_accessories', 'Cupping Accessoires'), ('supplementen', 'Voedingssupplementen'), ('vitamines', 'Vitamines & Mineralen'), ('kruiden', 'Kruidentherapie'), ('oliën', 'Etherische Oliën'), ('massage', 'Massage Producten'), ('wellness', 'Wellness & Ontspanning'), ('boeken', 'Therapeutische Boeken'), ('apparatuur', 'Medische Apparatuur')], help_text='Product categorie', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Actief in webshop'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Voorraad aantal'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('shipping', 'Verzendadres'), ('billing', 'Factuuradres')], default='shipping', max_length=10)),
                ('first_name', models.CharField(max_length=100, verbose_name='Voornaam')),
                ('last_name', models.CharField(max_length=100, verbose_name='Achternaam')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Bedrijf (optioneel)')),
                ('street_address', models.CharField(max_length=255, verbose_name='Straat')),
                ('house_number', models.CharField(max_length=10, verbose_name='Huisnummer')),
                ('house_number_addition', models.CharField(blank=True, max_length=10, verbose_name='Toevoeging')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Postcode')),
                ('city', models.CharField(max_length=100, verbose_name='Plaats')),
                ('province', models.CharField(default='Nederland', max_length=100, verbose_name='Provincie')),
                ('country', models.CharField(default='Nederland', max_length=100, verbose_name='Land')),
                ('is_default_shipping', models.BooleanField(default=False, verbose_name='Standaard verzendadres')),
                ('is_default_billing', models.BooleanField(default=False, verbose_name='Standaard factuuradres')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adres',
                'verbose_name_plural': 'Adressen',
                'ordering': ['-is_default_shipping', '-is_default_billing', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_orders', to='api.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipping_orders', to='api.address'),
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Winkelwagen',
                'verbose_name_plural': 'Winkelwagens',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('newsletter_subscription', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.shoppingcart')),
            ],
            options={
                'verbose_name': 'Winkelwagen Item',
                'verbose_name_plural': 'Winkelwagen Items',
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
