# Generated by Django 5.2.5 on 2025-08-15 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mollie_payment_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(blank=True, max_length=50)),
                ('webhook_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='api.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mollie_payment_id'], name='api_payment_mollie__604b43_idx'), models.Index(fields=['status'], name='api_payment_status_4896ee_idx')],
            },
        ),
    ]
